services:

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command:
      - -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    command:
      # Must re-specify config.file since we're overriding the default command
      - --config.file=/etc/prometheus/prometheus.yml
      # Enables the /api/v1/write remote-write receiver that Alloy pushes to
      - --web.enable-remote-write-receiver
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  tempo:
    image: grafana/tempo:latest
    command:
      - -config.file=/etc/tempo.yml
    ports:
      - "3200:3200"
      - "4319:4317"
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml

  alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - ./runtime_logs:/var/log/logapp
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy

volumes:
  loki-data:
  grafana-data:
  prometheus-data: